checks:
  php: true
filter:
  excluded_paths:
      - tests/*
build:
  environment:
    php:
      version: 7.4
  dependencies:
    before:
      - composer require phpunit/phpunit ^9.0
  tests:
    override:
      -
        command: vendor/bin/phpunit
          coverage:
            file: tests/report/clover.xml
              format: php-clover
